# Generated by Django 4.2.15 on 2024-08-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=36, unique=True)),
                ('isRentable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('isHd', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
