# Generated by Django 4.2.15 on 2024-08-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_movie_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
