# Generated by Django 4.2.15 on 2024-08-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_movie_ishd_alter_movie_isrentable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='isHd',
            new_name='isHD',
        ),
    ]
